
[env]
WINIT_X11_SCALE_FACTOR = "1"
term = "xterm-256color"


[font.normal]
family = "Iosevka Comfy"
# family = "IosevkaTerm Nerd Font"
# family = "IosevkaTerm Nerd Font Mono"
# style = "Meslo Nerd Font"
# style = "Light"

[font]
size = 23.4

[keyboard]
bindings = [
#  { key = "Space", mods = "Alt", action = "sh $HOME/scripts/fontsize" }
  {key = "=", mods = "Control", command = { program = "bash", args = ["/home/sakuya/scripts/fontsize.sh"] }},
  {key = "-", mods = "Control", command = { program = "bash", args = ["/home/sakuya/scripts/fontsize.sh"] }},
]

[general]
import = [
  # "~/.alacritty-themes/themes/alabaster_dark.toml"
  # "~/.alacritty-themes/themes/blood_moon.toml"
  # "~/.alacritty-themes/themes/campbell.toml"
  # "~/.alacritty-themes/themes/hyper.toml"
  # "~/.alacritty-themes/themes/alabaster_dark.toml"
  # "~/.alacritty-themes/themes/github_dark_high_contrast.toml"
  # "~/.alacritty-themes/themes/gruvbox_light.toml"
  # "~/.alacritty-themes/themes/noctis-lux.toml"
  # "~/.alacritty-themes/themes/everforest_light.toml"
  # "~/.alacritty-themes/themes/papertheme.toml"
  # "~/.alacritty-themes/themes/github_light_tritanopia.toml"  
  # "~/.alacritty-themes/themes/kanagawa_dragon.toml"  
  # "~/.alacritty-themes/themes/rose-pine.toml"
  # "~/.alacritty-themes/themes/argonaut.toml"
  # "~/.alacritty-themes/themes/tokyonight_night.toml"
  # "~/.alacritty-themes/themes/rose-pine-dawn.toml"
  "~/.alacritty-themes/themes/fogbell.toml"
  ]

